### ISSUE TITLE
style-loader breaks source maps in Firefox 59

### ISSUE THREAD

**Issue by robertjk** [webpack-contrib/style-loader#303]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

When I have `style-loader` in my CSS loaders chain, the source maps do not work in Firefox. I see  error messages in the Developer Tools console like the one below. Setting `convertToAbsoluteUrls: true` doesn't change the situation.

`Source map error: Error: sourceMapURL could not be parsed
Resource URL: blob:http://localhost:8080/3a52944e-4117-4d8d-98d6-32cd525beae9
Source Map URL: data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi9ob21lL3JvYmVydC9wcm9ncmFtbWluZy93ZWJwYWNrLXBsYXlncm91bmQvc3JjL2NvbXBvbmVudC1hL3NyYy9jb21wb25lbnQtYS9jb21wb25lbnQtYS5zY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUlBO0VBRUksY0FBYTtFQUNiLHVCQUFzQjtFQUN0QixrQkFBaUIsRUFZcEI7RUFWRztJQUNJLG1CQVhJO0lBWUosaUJBQWdCO0lBQ2hCLGlCQUFnQixFQUNuQjtFQUVEO0lBQ0ksbUJBaEJNLEVBaUJUIiwiZmlsZSI6ImNvbXBvbmVudC1hLnNjc3MiLCJzb3VyY2VzQ29udGVudCI6WyIkbWFyZ2luOiA1cHg7XG4kcGFkZGluZzogMTBweDtcblxuXG4uQ29tcG9uZW50QSB7XG5cbiAgICBkaXNwbGF5OiBmbGV4O1xuICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG4gICAgZmxleC13cmFwOiBub3dyYXA7XG5cbiAgICAmLUhlYWRlciB7XG4gICAgICAgIG1hcmdpbi1ib3R0b206ICRtYXJnaW47XG4gICAgICAgIGJhY2tncm91bmQ6ICNlZWU7XG4gICAgICAgIGZvbnQtc2l6ZTogMS41ZW07XG4gICAgfVxuXG4gICAgJi1Cb2R5IHtcbiAgICAgICAgcGFkZGluZy1sZWZ0OiAkcGFkZGluZztcbiAgICB9XG5cbn1cbiJdLCJzb3VyY2VSb290IjoiIn0=[Learn More]`

When I remove `style-loader` and use `extract-text-webpack-plugin` instead, the source maps start to work. In addition even if `style-loader` is used, everything works fine in Chrome Developer Tools.

I created an example repo with the problem: https://github.com/robertjk/webpack-firefox-source-map-error.

**What is the expected behavior?**

I expect source maps to work properly in Firefox, as they do when `style-loader` is not used.

**Additional info**

Firefox version: 59.0b8
Node.js verison: 9.5.0
`webpack` version: 3.11.0
`style-loader` version: 0.20.1

**Comment by evilebottnawi** [comment]
@robertjk Thanks!

**Comment by evilebottnawi** [comment]
@robertjk Confirm, let's investigate, maybe bug in firefox

**Comment by robertjk** [comment]
@evilebottnawi What do you mean by "Confirm"? Yes, it may be a bug in Firefox, as in Chrome everything works fine.

**Comment by evilebottnawi** [comment]
@robertjk Confirm is mean it are not you local or configuration or configuration problems :smile:

**Comment by robertjk** [comment]
@evilebottnawi Oh, I get it :).

**Comment by evilebottnawi** [comment]
Maybe we should search better way for https://github.com/webpack-contrib/style-loader/blob/master/lib/addStyles.js#L366

**Comment by evilebottnawi** [comment]
In firefox@59 all works fine. Seems bug in firefox. Only `wds` failed, but not related to `style-loader`.

**Comment by mikehdt** [comment]
I'm not sure what you mean by "In firefox@59 all works fine" -- I'm seeing `style-loader` sourcemaps failing in both Firefox 59 and current dev version 60?

**Comment by redeyes2015** [comment]
I think "Only `wds` failed" may not be accurate.

With the [example repo](https://github.com/robertjk/webpack-firefox-source-map-error) provided by the issue opener, I ran:

```shell
> yarn webpack --config ./webpack.style-loader.babel.js
> serve dist
```

Firefox 58 and Firefox 60 (Developer Edition) both print "Source map error".

**Comment by caimaturo** [comment]
The same is happening to me. It's breaking my Vue app on Firefox only (works fine on Chrome, Edge and Safari). I'm also using CSS variables as mentioned [here](https://github.com/webpack-contrib/css-loader/issues/640).

Firefox version: 59.0.2
Node.js verison: 9.5.0
`webpack` version: 4.4.1
`style-loader` version: 0.20.3

**Comment by evilebottnawi** [comment]
I think it is firefox bug, somebody can take care this issue and create report to firefox bugs tracker?

**Comment by redeyes2015** [comment]
I think this is the bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1451274,
and it directs to https://github.com/mozilla/source-map/issues/275.

The issue is:

> source-map uses a phony URL parser that does:
> 
> var urlRegexp = /^(?:([\w+\-.]+):)?\/\/(?:(\w+:\w+)@)?([\w.-]*)(?::(\d+))?(.*)$/;

So, one must at least write `/*# sourceMappingURL=//somedomain/some.map` and Blob URL could never pass.

It seems to be a long way for a fix to eventually land in Firefox. 😢

**Comment by heyflo** [comment]
I'm having the same problem with webpack 4 (lastest version) and firefox dev edition (lastest version too).
I tried for some hours to implement correct sourcemaps for my dev environment with webpack and I just could not solve it. Just to find out it's a known issue and it's working perfectly on Chrome.

Here is what I get :
![firefox-sourcemaps-webpack4](https://user-images.githubusercontent.com/31403513/41988014-33393bea-7a3b-11e8-8749-a305246af5dd.gif)

**Comment by elliottregan** [comment]
Anyone find a temporary workaround? Any chance a plugin could reformat the URL to work?

**Comment by zetaraku** [comment]
@elliottregan It is a problem in Firefox, so you can just use Chrome for now.

**Comment by wokejacqueline** [comment]
This is still happening to me in Firefox 61.02.  Is this a confirmed Firefox bug?  It's been happening since 59 for me. No issues in Safari.

**Comment by elliottregan** [comment]
@wokejacqueline This issue over in the main Webpack repo has some more info than this issue has: https://github.com/webpack/webpack/issues/1194 I haven't found any devTool option that works, even though others have. 

There are three or four projects that could offer a fix, but it seems like the project maintainers keep saying "the issue is over there"...for the last three years or so.

**Comment by Epskampie** [comment]
A solution is ditching `style-loader` and moving to [css-hot-loader](https://github.com/shepherdwind/css-hot-loader)

`npm install css-hot-loader mini-css-extract-plugin --save-dev`

If your config was this:

    {
        test: /\.css$/,
        use: [
            {
                loader: 'style-loader',
                options: { sourceMap: enableSourcemap },
            },
            {
                loader: 'css-loader',
                options: { url: false, sourceMap: enableSourcemap },
            },
            { loader: 'sass-loader', options: { sourceMap: enableSourcemap } },
        ],
    }

It will now be this:

    {
        test: /\.css$/,
        use: [
            {
              loader: 'css-hot-loader',
            },
            {
              loader: MiniCssExtractPlugin.loader,
            },
            {
              loader: 'css-loader',
              options: { url: false, sourceMap: true },
            },
        ],
    }

Hot reloading works, source maps work

**Comment by evilebottnawi** [comment]
@Epskampie you very very very increase build time, you don't need extract css in dev env

**Comment by Epskampie** [comment]
Build time seems OK here, but my project is not huge yet. If you have a better solution that works on firefox i'd love to hear it. :-D

**Comment by Epskampie** [comment]
Good to hear, if there is anything i can do to help, let me know!

**Comment by mbalaam** [comment]
Firefox Nightly 67 seems to have a fix in place for this issue

**Comment by ogonkov** [comment]
Seems fixed as of Firefox 67.0.1

**Comment by elliottregan** [comment]
Fingers crossed the next release has working sourcemaps... 🤞

**Comment by minhtranite** [comment]
I just update to version `1.0.0` and it still not working. here is my loaders config:

```
...
{
          test: /\.scss$/,
          exclude: /@ckeditor/,
          use: [
            HOT
              ? {
                  loader: 'style-loader',
                }
              : MiniCssExtractPlugin.loader,
            {
              loader: 'css-loader',
              options: {
                sourceMap: true,
              },
            },
            {
              loader: 'postcss-loader',
              options: {
                sourceMap: true,
              },
            },
            {
              loader: 'sass-loader',
              options: {
                includePaths: [path.join(__dirname, 'node_modules')],
                outputStyle: PROD ? 'compressed' : 'expanded',
                sourceMap: true,
              },
            },
          ],
        },
....
devtool: PROD ? '#sourcemap' : '#cheap-eval-source-map',
...
```

**Comment by evilebottnawi** [comment]
@robertjk please create minimum reproducible test repo, i think bug on firefox side

**Comment by minhtranite** [comment]
I think so, Thank you! The warning message on Firefox are gone but source map still not work.

**Comment by evilebottnawi** [comment]
@mikehdt yep, source maps still not work in firefox :disappointed: try to search bug in their bug tracker

**Comment by evilebottnawi** [comment]
Firefox bug:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1451274
- https://bugzilla.mozilla.org/show_bug.cgi?id=1543896 (previously we use blob)

Sorry we can't do something on our side here, please write to firefox bug tracker

**Comment by Austaras** [comment]
works fine for me in Firefox after 1.0 release

**Comment by evilebottnawi** [comment]
@Austaras it is strange, can you provide example?

**Comment by Austaras** [comment]
@evilebottnawi [this repo](https://github.com/Austaras/boilerplate/tree/4e0fda5085d1c44e3796d80e13176ab630b05477)
Firefox 69.0b10-1

**Comment by evilebottnawi** [comment]
@Austaras thanks, maybe firefox fix bug in latest release, i have problems on `68.0.1 (64-bit)`

**Comment by minhtranite** [comment]
@Austaras I clone and run you example on Firefox nightly but it still not work

<img width="1675" alt="Screen Shot 2019-08-06 at 10 10 45 PM" src="https://user-images.githubusercontent.com/5418628/62552067-3b8a4280-b897-11e9-9d70-48f051d4addc.png">

**Comment by Austaras** [comment]
@minhtranite 
that's wired. It works in Firefox 58 in my machine. Did you turn on enable sourcemap in developer tool?
![pic](https://user-images.githubusercontent.com/15013925/62553003-2c0ff700-b8a1-11e9-87ec-e63d33bcf7e5.png)

**Comment by bn4z** [comment]
Hi! If the info can help: I'm using **Firefox 69.0b11 (64-bit)** on Windows 10. Upgrading from style-loader **0.23.1** to **1.0.0** removed the message `Source map error: TypeError: Invalid URL: .` in the console.

**Comment by loganfsmyth** [comment]
I looked into this on the Firefox side, and I'm not sure I'd consider this a Firefox bug, but rather a case where Chrome may have more fallbacks to handle invalid sourcemaps. We can certainly look into potentially handling this, but the map as it stands does not contain valid `sources` for this context.

In the case of the example provided in the initial post, the `extract-text-webpack-plugin` example map that works has
```
  "sources": [
    "webpack:///./src/component-a/src/component-a/component-a.scss",
    "webpack:///./src/component-b/src/component-b/component-b.scss"
  ],
```
and the map `style-loader` map that doesn't work has
```
  "sources": [
    "/tmp/webpack-firefox-source-map-error/src/component-a/src/component-a/component-a.scss"
  ],
```
with the critical difference being that the first is an absolute URL, and the second is only a path-absolute URL, meaning that the second one requires a valid base URL in order to be resolved into a full URL (and the blob: URL used in this case is not a valid base).

When this map is loaded, it is resolved based on the URL of the CSS file, so you end up with
```
new URL("/folder/file.scss", "blob:http://localhost:8080/some-hash")
```
which then throws because you can't have a filepath relative to a blob URL. It seems like Chrome may have some fallback here that just uses the overall page's URL if no other valid base is found.

For `style-loader`, it seems that Webpack does not rewrite the URLs in `sources` by passing them through Webpack's `output.devtoolModuleFilenameTemplate` template, causing the issue. I'm not familiar enough with Webpack to know if there's some way to make that happen, but it certainly seems like the ideal solution.

**Comment by elliottregan** [comment]
@loganfsmyth Thanks for doing all this research. I had a feeling it was a Webpack bug, because source maps have worked in Gulp and every other build tool I've used. 

Anybody know how we can get this escalated to someone who can merge PRs? The last PR for webpack-contrib that I got involved in has been sitting open since 2017. 🙄

**Comment by alvaro-escalante** [comment]
For me in turned out to be the React Developer tools add on, the moment I disabled it, the source maps changed from inline to the proper sass partial. It works with this set up:
``` 
rules: [{
  test: /\.scss$/, 
  use: [
    'style-loader', 
    'css-loader?sourceMap',
    'sass-loader?sourceMap'
   ]
}]```

**Comment by Grsmto** [comment]
@alvaro-escalante does that mean it's a React Dev Tools issue? I searched but I didn't find any issue reported on their repo.

**Comment by elliottregan** [comment]
It's not a React Dev Tools problem. This issue has more info and discussion: https://github.com/webpack/webpack/issues/1194

**Comment by alvaro-escalante** [comment]
> @alvaro-escalante does that mean it's a React Dev Tools issue? I searched but I didn't find any issue reported on their repo.

Actually even thou it was React dev tools that affected my sourcemaps on firefox, it turned out to be a setting on my package.json that trigger the the style-loader to not work properly.

It was the -D flag on dev script. Once I remove that it worked well with this

```
{
  module: {
    rules: [
      {
        test: /\.scss$/,
        include,
        exclude,
        use: [
          {
            loader: MiniCssExtractPlugin.loader, 
            options: { hmr: true }
          },
          'css-loader?sourceMap', 
          'sass-loader?sourceMap'
        ]
      }
    ]
  },
  plugins: [ new MiniCssExtractPlugin()]
}
```

**Comment by elliottregan** [comment]
I am not using a `-D` flag, and I can't find it mentioned in the docs. I've only seen that for `npm i -D package-name`.

Any idea what that could have been interpreted as?

It's confusing me because this doesn't really match what others have discovered, unless it is triggering some unexpected behavior. There are definitely race conditions that cause it to work occasionally, and maybe an errand flag can clue us in.

**Comment by evilebottnawi** [comment]
Still broken :disappointed:

**Comment by evilebottnawi** [comment]
Sorry for delay, looks reasonable https://github.com/webpack-contrib/style-loader/issues/303#issuecomment-547223707, I will look at this deeply

**Comment by loganfsmyth** [comment]
@evilebottnawi Are you sure it's still broken? I think https://bugzilla.mozilla.org/show_bug.cgi?id=1607639 has fixed this. When I run the reproduction example, I see SCSS files in the style editor in FF.
<img width="686" alt="Screen Shot 2020-07-25 at 1 17 17 PM" src="https://user-images.githubusercontent.com/132260/88465612-739ef100-ceff-11ea-96fa-621cbb5bf4f5.png">

**Comment by evilebottnawi** [comment]
Strange, I reproduce this problem on FF? Can you provide version of FF?

**Comment by mbalaam** [comment]
@evilebottnawi I found I had less problems with Firefox if I set this in my plugin settings:

`     new webpack.SourceMapDevToolPlugin({
        filename: false, //inline all source maps - best Firefox compatability
      }),
`

**Comment by minhtranite** [comment]
It seems that now it's works on Firefox 79

![image](https://user-images.githubusercontent.com/5418628/89114049-a4a09800-d4a2-11ea-8b55-c0e59680cb01.png)

**Comment by evilebottnawi** [comment]
Fixed in Firefox 79, It's been a long time, anyway I want to test it on other browsers, maybe we really can improve it
